# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b935300bddbc1c0a25bf44d2a3f7531af5b5ffbe84fef57a146402a8958d582b2c772cf828d899fa76ad356f19c88a8134136d5667a064a598d5dc2d2977df7f

test:
  secret_key_base: 18731679b1a3e6908c90e855d60ea3978f9929dc051f7fda0e24bde20037205ebba4c98a39a93913be64402c589898ecf9b2c8e6752f3163c264e2cae173e526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
